### ISSUE TITLE
Hello, I want to ask about saving for the galaxy editor

### ISSUE THREAD

**Issue by SugarCaneEnjoyer** [Nro001/Nro-Galaxy-Editor#1]
I hate to disturb but this is the only thing I can't seem to get past. I edit my galaxy, then export it, after that I make a back up of my original save, use the galactic-object-modified method and copied and pasted to my gamestate. I then use the archive option to create the .sav file and when I add it back to my saves it gives me 2 errors, one where all the planets and star are gone when I load up, and one where the save is just corrupted.

Any advice?

If you need me to add my save, I can

**Comment by Nro001** [comment]
There's two possibility why that happened
1. "galactic_object={" is duplicated
2. You created a new .sav file instead of overwriting the zip itself
Here are the solutions for each
1. Using Notepad++ search for "galactic_object={", usually if you just copied all contents galactic-object-modified instead of the {, you would get galactic_object=galactic_object={. It should only be "galactic_object={"
3. Open the zip file itself and just drag your modified gamestate there and overwrite the existing gamestate, archiving a new .sav file would require following this [wiki](https://stellaris.paradoxwikis.com/Save-game_editing).

If none of them works, let me know and give me your save-file also

**Comment by SugarCaneEnjoyer** [comment]
Ok I see now, I've been creating a new save file forgetting to overwrite the original, all my stars are back in the galaxy now. Thank you for the help.
